project = ""
ibmcloud_api_key = ""
ssh_key_name = ""
# tags = [ "owner:timro" ]
zt_network = ""
# resource_group_name = ""
# spoke_vpc_count = 2
# region = "us-east"
# vpc_subnet_range = "10.16.64.0/18"
# zone = "us-east-2"